## Python Assignment -7

In [1]:
# generating the output with powers os input using vander function
import numpy as np
a = np.array([1,2,3,5])
Y = 4
np.vander(a, increasing =True )

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [2]:
# Executing the above matrix using another method

np.column_stack([a**(Y-1-i) for i in range(Y)])

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]], dtype=int32)

In [3]:
# Using third method

np.matrix([a**(Y-i-1) for i in range(Y)])

matrix([[  1,   8,  27, 125],
        [  1,   4,   9,  25],
        [  1,   2,   3,   5],
        [  1,   1,   1,   1]], dtype=int32)

In [4]:
# Given example

b = np.array([1,2,3,4,5,6,7,8,9,10])
b

n = 10
k = 4

In [5]:
input_arr = np.array(b*n)

len(input_arr)

10

In [6]:
# Testing the output using for loop

for j in range(n-k+1):
        out = input_arr[j:j+4].sum()/k
      

In [7]:
# Creating the output in the form of an array

out_arr = np.array([input_arr[j:j+4].sum()/k for j in range(n-k+1) ])

In [8]:
out_arr

array([25., 35., 45., 55., 65., 75., 85.])

In [9]:
# Taking the input as mentioned in the asignment and performing the programe for the desired output array

n = 13
k = 3
input_array = np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])

input_array

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [10]:
# Using list comprehesion in numpy for generating an output array

output_array = np.array([input_array[j:j+3].sum()/k for j in range(n-k+1) ])

In [11]:
output_array

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

#### The above output array is the result satisfying all the conditions mentioned in the question